name: Flutter Nightly Build

on:
  schedule:
    # schedule build every week
    - cron: "0 0 * 12 0"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
